version: '3.8'

services:
  app:
    image: dunglas/frankenphp:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
      - ./public:/var/www/html/public
      - ./database:/var/www/html/database
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:tanFUPgqNDLP3TUSxwjDo31jd1/IHP+UrZoJGObNMso=
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      OCTANE_SERVER: frankenphp
      OCTANE_WORKER_NUM: 4
    ports:
      - "8080:80"
    command: "php artisan octane:start --server=frankenphp --max-requests=500 --workers=4"

  scheduler:
    image: dunglas/frankenphp:latest
    container_name: laravel_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: |
      /bin/sh -c "while [ true ]; do
      php artisan schedule:run --verbose --no-interaction &
      sleep 60
      done"

  queue:
    image: dunglas/frankenphp:latest
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work --tries=3

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
