services:
    web:
        build:
            context: ./
            dockerfile: ./.docker/php/Dockerfile.local
        ports:
            - ${APP_PORT:-8000}:8000
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - ./:apps/${APP_NAME}
            - ./vendor/:apps/${APP_NAME}/vendor
        networks:
            - laraveloctane
        depends_on:
            - mysql
            - redis
            - minio
            - mailpit
    mysql:
        image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./database/mysql-test-data:/var/lib/mysql
        networks:
            - laraveloctane
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - -p${DB_PASSWORD}
            retries: 3
            timeout: 5s
    redis:
        image: redis:alpine
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        volumes:
            - ./database/redis-data:/data
        networks:
            - laraveloctane
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    laraveloctane:
        driver: bridge
