version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=local
      - APP_KEY=base64:$(openssl rand -base64 32)
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

  # Opcional: Adicionar um serviço para o banco de dados se você precisar de algo além do SQLite
  # db:
  #   image: nouchka/sqlite:latest
  #   volumes:
  #     - ./database:/var/www/html/database
