version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /app
    restart: unless-stopped
    ports:
      - "3333:80"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:tanFUPgqNDLP3TUSxwjDo31jd1/IHP+UrZoJGObNMso=
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
    tty: true

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  # Volumes needed for Caddy certificates and configuration
  caddy_data:
  caddy_config: