version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "3333:80"
    volumes:
      - ./:/app/
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:tanFUPgqNDLP3TUSxwjDo31jd1/IHP+UrZoJGObNMso=
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
