[phases.build]
cmds = ["composer install --optimize-autoloader --no-dev"]

[phases.setup]
cmds = [
    "composer require symfony/runtime",
    "composer require laravel/octane spatie/laravel-frankenphp",
    "npm install --production",
]

[phases.start]
cmds = [
    "php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000",
]

[phases.runtime]
envs = { "APP_ENV" = "production", "OCTANE_SERVER" = "frankenphp"}

[[phases.runtime.packages]]
name = "php83"

[[phases.runtime.packages]]
name = "nodejs"

[[phases.runtime.packages]]
name = "npm"

[[phases.runtime.packages]]
name = "composer"

[phases.cache]
paths = ["vendor", "node_modules"]
